services:
  openclaw:
    image: 'openclaw/openclaw:latest'
    command:
      - node
      - openclaw.mjs
      - gateway
      - '--allow-unconfigured'
      - '--port'
      - '18789'
    environment:
      - OPENCLAW_GATEWAY_TOKEN=${OPENCLAW_GATEWAY_TOKEN}
    x-runtipi:
      is_main: true
      internal_port: '18789'
x-runtipi:
  schema_version: 2
